export const environment = {
  production: import.meta.env.VITE_USE_FAKE_API === 'false',
  platformProviderApiBaseUrl: import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000/api/v1',
  platformProviderSignInEndpointPath: '/authentication/sign-in',
  platformProviderSignUpEndpointPath: '/authentication/sign-up',
  platformProviderProfilesEndpointPath: '/profiles',
  platformProviderEquipmentEndpointPath: '/equipment',
  platformProviderRentalRequestsEndpointPath: '/rental-requests',
  platformProviderRentalsEndpointPath: '/rentals',
  platformProviderDeliveriesEndpointPath: '/deliveries',
  platformProviderEquipmentReturnsEndpointPath: '/equipment-returns',
  platformProviderMaintenancesEndpointPath: '/maintenances',
  platformProviderIncidentsEndpointPath: '/incidents',
  platformProviderEquipmentCategoriesEndpointPath: '/equipment-categories',
  platformProviderSubscriptionPlansEndpointPath: '/subscription-plans',
  platformProviderUserSubscriptionsEndpointPath: '/user-subscriptions',
};
